USE MASTER
CREATE DATABASE TPC_equipo24_BD;
USE TPC_equipo24_BD;

go
CREATE TABLE Usuarios(
	ID BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(50) NOT NULL UNIQUE,
	Clave VARCHAR(20) NOT NULL CHECK(Clave >= 8),
	Puesto INT NOT NULL	
);
go
CREATE TABLE Datos_Personales(
    IdDatosPersonales BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1) FOREIGN KEY REFERENCES Usuarios(Id),
	Legajo BIGINT NOT NULL UNIQUE,
    Dni VARCHAR(20) NULL,
    Nombre VARCHAR(100) NOT NULL,
	Apellido VARCHAR(100) NOT NULL,
    FechaNacimiento DATE NOT NULL,
    Genero CHAR NULL,
    Telefono VARCHAR(15) NULL,
    Email VARCHAR(140) NULL,
    Domicilio VARCHAR(200) NOT NULL
);
go
CREATE TABLE Gerente(
	Id BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(100) NOT NULL,
	Apellido VARCHAR(100) NOT NULL,
	Estado BIT NOT NULL
);
go
CREATE TABLE Mesero(
	Id BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(100) NOT NULL,
	Apellido VARCHAR(100) NOT NULL,
	Estado BIT NOT NULL
);
go
CREATE TABLE Mesa(
	Id BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Id_Factura INT,
	Estado BIT NOT NULL
);
go
CREATE TABLE Pedido(
	IdPedido BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Estado BIT NOT NULL,
	FechaHoraCreado DATETIME
);
go
CREATE TABLE ItemPedido(
	IdItemPedido BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Cantidad INT NOT NULL CHECK(Cantidad > 0),
	PrecioUnitario MONEY NOT NULL CHECK(PrecioUnitario > 0)
);
go
CREATE TABLE Factura(
	IdFactura BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Id_Mesa BIGINT NOT NULL,
	Id_Pedido BIGINT NOT NULL,
	Id_FormaDePago INT NOT NULL, 
	TipoFactura CHAR,
	Cantidad INT NOT NULL,
	PrecioTotal MONEY NOT NULL CHECK(PrecioTotal > 0),
	FechaCreacion DATETIME
);
go
CREATE TABLE FormaDePago(
	Id SMALLINT NOT NULL PRIMARY KEY,
	Nombre VARCHAR(50) NOT NULL
);
go
CREATE TABLE Resenias(
    IdInscripcion BIGINT NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES Mesero(Id),
    Fecha DATE NOT NULL DEFAULT(GETDATE()),
    Observaciones VARCHAR(MAX) NOT NULL,
    Puntaje DECIMAL(3, 1) NOT NULL,
    Inapropiada BIT NOT NULL DEFAULT(0)
);
go
CREATE TABLE Insumo(
	IdInsumo BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(50) NOT NULL,
	Tipo VARCHAR(50) NOT NULL,
	Precio MONEY NOT NULL CHECK(Precio > 0),
	Cantidad INT NOT NULL,
);











